### ISSUE TITLE
Duplicate Audio Activity Imports

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-authored-profiles#79] opened 2019-10-10 14:21 UTC
Just noticed there are two audio activity types with different definitions:

http://xapi.vocab.pub/activity-types/index.html

It looks like the original import that used the video definition is still in the database. 

I think it's a matter of clearing the graph and reimporting it. Not a big deal, but the cause is that there are two different versions and definitions:

https://github.com/adlnet/xapi-authored-profiles/blob/master/audio/audio.ttl

https://github.com/adlnet/xapi-authored-profiles/blob/master/audio/v1.0/audio.ttl

**Comment by FlorianTolk** [comment] 2019-10-11 14:39
Thanks for the heads up, I'll look into it

**Comment by FlorianTolk** [comment] 2019-10-11 14:55
The issue is actually with the ttl on github
I will address this to the author of the profile in case there is something else that is incorrect

**Comment by FlorianTolk** [comment] 2019-10-17 18:57
Should be fixed now!
Thanks again for bringing this to my attention!

**Closed** 2020-02-07 16:19 UTC
